backend/protected/controllers/AboutController.php
<?php

class AboutController extends Controller
{

	public function actionIndex()
	{
		$this->pageTitle = 'About Us - '.$this->pageTitle;
		$this->layout='//layouts/column1';

		$data = array(
			'title'=>$this->setting['about_whoweare_title'],
			'content'=>$this->setting['about_whoweare_content'],
			);

		$this->render('index', array(	
			'data' => $data,
		));
	}

	public function actionWho_we_are()
	{
		$this->pageTitle = 'About Us - '.$this->pageTitle;
		// $this->layout='//layouts/column1';
		$this->layout=false;

		$data = array(
			'title'=>$this->setting['about_whoweare_title'],
			'content'=>$this->setting['about_whoweare_content'],
			);

		// header('Content-type: application/json');
		// echo json_encode(
		// 		array(
		// 			'status'=>200,
		// 			'msg'=>'',
		// 			'data'=>$data,
		// 		)
		// 	);
		$this->renderPartial('ajaxContent', array('data'=>$data), false, true);
	}

	public function actionOurteam()
	{
		$this->pageTitle = 'About Us - '.$this->pageTitle;
		// $this->layout='//layouts/column1';

		$data = array(
			'title'=>$this->setting['about_ourteam_title'],
			'content'=>$this->setting['about_ourteam_content'],
			);

		$this->renderPartial('ajaxContent', array('data'=>$data), false, true);
	}

	public function actionVisimisi()
	{
		$this->pageTitle = 'About Us - '.$this->pageTitle;
		// $this->layout='//layouts/column1';

		// $this->render('visimisi', array(	
		// ));
		$data = array(
			'title'=>$this->setting['about_visimisi_title'],
			'content'=>$this->setting['about_visimisi_content'],
			);

		$this->renderPartial('ajaxContent', array('data'=>$data), false, true);
	}

	public function actionWorkwithus()
	{
		$this->pageTitle = 'About Us - '.$this->pageTitle;
		// $this->layout='//layouts/column1';

		// $this->render('workwithus', array(	
		// ));
		$data = array(
			'title'=>$this->setting['about_workwithus_title'],
			'content'=>$this->setting['about_workwithus_content'],
			);

		$this->renderPartial('ajaxContent', array('data'=>$data), false, true);
	}

}

backend/protected/views/about/ajaxContent.php
 <h2><?php echo $data['title'] ?></h2> <div class="clear height-30"></div>
                <?php echo $data['content'] ?>

backend/protected/views/about/faq.php
<div class="content-text text-center mw-836 tengah">
	<h4>SERTIFIKASI</h4>
	<p>&nbsp;</p>
	<?php 
	$criteria_faq = new CDbCriteria();
	$criteria_faq->order = "sort ASC";
	$model_faq = Faq::model()->findAll($criteria_faq);
	?>
	<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
	<?php
	$i = 1;
	foreach ($model_faq as $key => $value): ?>
		  <div class="panel panel-default">
		    <div class="panel-heading" role="tab" id="heading<?php echo $key ?>">
		      <h5 class="panel-title">
		        <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapse<?php echo $key ?>" aria-expanded="true" aria-controls="collapse<?php echo $key ?>">
		          <?php echo $value->question; ?>
		        </a>
		      </h5>
		    </div>
		    <div id="collapse<?php echo $key ?>" class="panel-collapse collapse <?php echo ($i==1)? 'in':''; ?>" role="tabpanel" aria-labelledby="heading<?php echo $key ?>">
		      <div class="panel-body">
		        <p><?php echo strip_tags($value->answer); ?></p>
		      </div>
		    </div>
		  </div>

		<?php $i++; ?>
	<?php endforeach; ?>
	</div>
	<p>&nbsp;</p>
</div>

backend/protected/views/about/index.php
<section class="outer-inside-middle-content back-white">
  <div class="prelatife">
    <div class="tops-cont-insidepage prelatife"> 
        <div class="picts-fullw"><img src="<?php echo $this->assetBaseurl; ?>inside-pg-abouts-top.jpg" alt="" class="img-responsive"></div>

        <div class="pos-abs-fullw tp50p">
          <div class="tengah insd-container text-center content-up">
             <h1 class="titles-pages-sub">Teknologi Xado</h1>
             <div class="clear height-15"></div>
             <p>Sebuah inovasi untuk perlindungan dan perbaikan</p>
            <div class="clear"></div>
          </div>
        </div>
    </div>

    <div class="clear"></div>
  </div>

  <section class="middle-inside-page-white prelatife">
      <div class="prelatife container">
          <div class="posin-pagincontt-about">
            <div class="text-center">
              <div class="outers-back-top-ppagin-contabout tengah">
                  <ul class="list-inline" id="myTabs">
                    <li class="active"><a href="#revitalisasi" id="revitalisasi-tab" role="tab" data-toggle="tab" aria-controls="revitalisasi" aria-expanded="true">REVITALISASI</a></li>

                    <li><a href="#manfaat" id="manfaat-tab" role="tab" data-toggle="tab" aria-controls="manfaat" aria-expanded="true">MANFAAT REVITALISASI</a></li>

                    <li><a href="#sertifikasi" id="sertifikasi-tab" role="tab" data-toggle="tab" aria-controls="sertifikasi" aria-expanded="true">SERTIFIKASI</a></li>

                    <li><a href="#faq" id="faq-tab" role="tab" data-toggle="tab" aria-controls="faq" aria-expanded="true">FAQ</a></li>

                    <li><a href="#testimoni" id="testimoni-tab" role="tab" data-toggle="tab" aria-controls="testimoni" aria-expanded="true">TESTIMONI</a></li>
                  </ul>
              </div>
            </div> <div class="clear"></div>
          </div>

          <div class="clear height-50"></div>
          <div class="clear height-50"></div>
          <div class="clear height-20"></div>

          <div class="tab-content">
            <div id="revitalisasi" data-id="1" class="tab-pane fade active in" role="tabpanel">
              <?php echo $this->renderPartial("//about/revitalisasi", array()); ?>
            </div>
            <div id="manfaat" data-id="2" class="tab-pane fade" role="tabpanel">
              <?php echo $this->renderPartial("//about/manfaat", array()); ?>
            </div>
            <div id="sertifikasi" data-id="3" class="tab-pane fade" role="tabpanel">
              <?php echo $this->renderPartial("//about/sertifikasi", array()); ?>
            </div>
            <div id="faq" data-id="4" class="tab-pane fade" role="tabpanel">
              <?php echo $this->renderPartial("//about/faq", array()); ?>
            </div>
            <div id="testimoni" data-id="5" class="tab-pane fade" role="tabpanel">
              <?php echo $this->renderPartial("//about/testimoni", array()); ?>
            </div>
            <div class="clear"></div>
          </div>
          
          <?php echo $this->renderPartial('//layouts/others_article', array()); ?>
          <div class="clear"></div>
      </div>
  </section>    

  <div class="clear"></div>
</section>
<script type="text/javascript">
  $(function(){
      $('#myTabs a').click(function (e) {
        e.preventDefault();
        var ids = $(this).attr('href');
        // alert(ids); return false;
        $(ids).tab('show');
      })
  });
</script>

backend/protected/views/about/manfaat.php
<div class="content-text text-center mw-836 tengah">
<h4>MANFAAT REVITALISASI</h4>

<p>Xado Revitalizant adalah senyawa kimia yang memberikan restorasi secara menyeluruh dan tanpa penggunaan alat/mesin, kepada permukaan metal di zona gesekan yang telah termakan umur. Xado memulihkan bagian dasar bentuk geometri dari logam tersebut dan melapisi dengan lapisan baru yang tahan lama dan mengandung komposisi bahan keramik-metal untuk melindungi keausan di masa mendatang. Revitalizant bekerja di manapun terdapat gesekan dan tekanan terjadi.</p>

<p><img alt="" class="about" src="<?php echo Yii::app()->baseUrl; ?>/images/static/baru_03.jpg"></p>

<p><img alt="" class="about" src="<?php echo Yii::app()->baseUrl; ?>/images/static/baru_10.jpg"></p>
<p>&nbsp;</p>
</div>

backend/protected/views/about/ourteam.php
<section class="outer-inside-middle-content back-white">
  <div class="prelatife container">
    <div class="tops-cont-insidepage"> <div class="clear height-50"></div>
        <div class="height-50"></div>
        <div class="height-50"></div>
        <div class="height-25"></div>
        <div class="tengah insd-container text-center content-up">
          <h1 class="title-pages">ABOUT</h1> <div class="clear height-10"></div>
          <div class="lines-chld-bgrey tengah"></div> <div class="clear height-25"></div>
          <span class="bigs"><?php echo $this->setting['about_header_title'] ?></span> <div class="clear"></div>
          <p><?php echo nl2br($this->setting['about_header_subtitle']) ?></p>
          <div class="clear"></div>
        </div>
    </div>

    <div class="clear"></div>
  </div>

  <div class="back-grey mh500">
    <div class="prelatife container">
        <div class="clear height-50"></div>
        <div class="outers-cont-bottom-abouts">
          <div class="topscont text-center">
            <ul class="list-inline">
              <li><a class="ajaxCall" href="<?php echo CHtml::normalizeUrl(array('/about/who_we_are')); ?>">who we are</a></li>
              <li><a class="ajaxCall" href="<?php echo CHtml::normalizeUrl(array('/about/ourteam')); ?>">our team</a></li>
              <li><a class="ajaxCall" href="<?php echo CHtml::normalizeUrl(array('/about/visimisi')); ?>">vision & mission</a></li>
              <li><a class="ajaxCall" href="<?php echo CHtml::normalizeUrl(array('/about/workwithus')); ?>">work with us</a></li>
            </ul>
          </div>
          <div class="clear height-50"></div><div class="height-35"></div>
          <div class="middles">
            
            <div class="mw920 tengah text-center">
                <h2><?php echo $this->setting['about_ourteam_title'] ?></h2> <div class="clear height-30"></div>
                <?php echo $this->setting['about_ourteam_content'] ?>
                <div class="clear height-50"></div>
<?php
$image = AboutImage::model()->findAll();
?>
            <?php foreach ($image as $key => $value): ?>
                <div class="ill-abouts"><img src="<?php echo Yii::app()->baseUrl; ?>/images/about/<?php echo $value->image ?>" alt="" class="img-responsive"></div>
                <div class="clear height-50"></div><div class="height-5"></div>
            <?php endforeach ?>             
                <div class="shares-text">
                  <span class="inline-t">SHARE</span>&nbsp;&nbsp; / &nbsp;&nbsp;<a href="#">FACEBOOK</a>&nbsp;&nbsp; / &nbsp;&nbsp;<a href="#">GOOGLE PLUS</a>&nbsp;&nbsp; / &nbsp;&nbsp;<a href="#">TWITTER</a>
                </div>

                <div class="clear"></div>
            </div>

            <div class="clear"></div>
          </div>

          <div class="clear"></div>
        </div>
      
      <div class="clear"></div> <div class="height-50"></div><div class="height-20"></div>
    </div>
  </div>
</section>
<script type="text/javascript">
  $(document).ready(function() {
    $(document).on('click', '.ajaxCall', function() {
        $.ajax({
              method: "GET",
              url: $(this).attr('href'),
              dataType: "html"
        })
        .done(function( data ) {
            alert(data); return false;
            // $('.bt-show-morehome').html($(data).find('.bt-show-morehome').html());
            // $('.list-gallery-data > .row').append($(data).find('.list-gallery-data > .row').html());
        });
        return false;
    });
});
</script>

backend/protected/views/about/revitalisasi.php
<div class="content-text text-center mw-836 tengah">
                      <h4>REVITALISASI</h4>
                      <p>
                            XADO Revitalizant merupakan bahan kimia yang menghadirkan solusi pemulihan total pada permukaan logam akibat keausan di area yang bergesekan. XADO memulihkan komponen-komponen sampai pada ukuran awalnya dan melapisinya dengan lapisan baru berupa keramik-metal yang sangat keras dan licin. Revitalizant bekerja dimana gesekan dan beban berlebih terjadi.
                      </p>
                      <p>&nbsp;</p>
                      <h4>BAGAIMANA CARA KERJA XADO?</h4>
                      <p>
                            Buktinya dapat dilihat pada gambar berikut ini.
                      </p>
                      <p>
                         <img alt="" class="about" src="<?php echo Yii::app()->baseUrl; ?>/images/static/about-product-xado.jpg">
                      </p>
                      <p>
                            Penting untuk dipahami bahwa Revitalizant bukanlah pelumas dan bukan hanya menutupi gejala keausan komponen logam. Revitalizant bekerja memperbaiki logam, atom demi atom, dimulai dari melapisi goresan-goresan dan bidang gesekan yang mengakibatkan keausan untuk kemudian melapisi permukaan logam tersebut dengan membentuk lapisan keramik-metal untuk mencegah keausan selanjutnya.
                      </p>
                      <p>
                         <img alt="" class="about" src="<?php echo Yii::app()->baseUrl; ?>/images/static/surface.jpg">
                      </p>
                      <p>&nbsp;</p>
                      <h4>Penggunaan XADO Revitalizant</h4>
                      <p>
                            Teknologi ini dapat digunakan secara luas dan mudah cara penggunaannya. Kami menghadirkan lebih dari 800 produk untuk industri umum dan militer, industri transportasi, dirgantara, kapal laut, peralatan pertanian dan medis, persenjataan maupun rumah tangga. Dimanapun, ketika terjadi friksi antara logam dengan logam (kompresor, gearbox, sistem hidrolik, mesin, segala macam bearing, open gear peralatan, mesin bubut, mesin pres dsb.) XADO Chemical Group telah mengembangkan berbagai produk yang mengandung revitalizant. Gemuk XADO diproduksi berdasarkan kondisi operasional unit, disesuaiakan dengan disain fiturnya, beban maksimum dsb. Hal ini membuatnya mampu untuk melakukan revitalisasi maksimal untuk segala macam mekanisme.
                      </p>
                      <p>
                         <img alt="" class="about" src="<?php echo Yii::app()->baseUrl; ?>/images/static/surface2.jpg">
                      </p>
                      <p>
                            Gel Revitalizant. Kami menghadirkan lebih dari 30 macam gel revitalizant spesial untuk perlindungan dan perbaikan dari berbagai unit kendaraan, industri dan peralatan olah raga menembak, begitu juga dengan revitalizant, dimana digunakan sebagai aditif untuk pembuatan berbagai gemuk maupun oli.
                      </p>
                      <p>
                            Oli mesin kendaraan dan industri. Kami menghadirkan lebih dari 100 produk untuk oli mesin kendaraan dan industri. Penggunaan revitalizant pada oli telah terbukti memiliki kemampuan operasional tak tertandingi.
                      </p>
                      <p>
                            Gemuk industri dan serba guna. Repairing Grease diproduksi dengan bahan dasar aditif modern dan superkonsentrat revitalizant dan ditujukan untuk pemulihan komponen. Karena kehadiran revitalizant pada lebih dari 50 macam Gemuk XADO memungkinkan perlindungan menyeluruh dari kendaraan dan mekanisme selama beroperasi.
                      </p>
              <div class="clear"></div>
          </div>

backend/protected/views/about/sertifikasi.php
<div class="content-text text-center mw-836 tengah">
<h4>SERTIFIKASI</h4>
<p>&nbsp;</p>
<?php 
	$model = Sertifikasi::model()->findAll();
?>
<div class="b-width-serti row">
	<?php foreach ($model as $key => $value): ?>
	<div class="col-md-6">
		<div class="list-sertifikat">
			<div class="hd"><?php echo $value->name; ?></div>
			<div class="clear height-0"></div>
			<div class="height-15"></div>
			<div class="pic"><img src="<?php echo Yii::app()->baseUrl.ImageHelper::thumb(100, 95, '/images/sertifikat/icon/'.$value->images_icon , array('method' => 'resize', 'quality' => '90')) ?>" alt=""></div>
			<div class="txt text-content">
				<?php echo strip_tags($value->description); ?>
			</div>
			<div class="clear height-10"></div>
			<div class="b-viewd"><a class="ser_fancy" href="<?php echo Yii::app()->baseurl; ?>/images/sertifikat/bg/<?php echo $value->images_big; ?>">View Detail</a></div>
		</div>
	</div>
	<?php // if ( (($key+1) % 2) == 0 ): ?>
		<!-- <div class="clear"></div> -->
	<?php // endif; ?>
	<?php endforeach; ?>
	
</div>
<p>&nbsp;</p>
</div>

backend/protected/views/about/testimoni.php
<div class="content-text text-center tengah">
	<h4>TESTIMONI</h4>
	<div class="mw-836 tengah">
		<p>Pengguna XADO berbagi dan menceritakan tentang kepuasan mereka setelah menggunakan produk untuk aneka kebutuhan mereka, dari otomotif hingga permesinan.</p>
	</div>
	<p>&nbsp;</p>

	<div class="list-testimonial">
		<div class="row">
			<?php for ($i=0; $i < 3; $i++) { ?>
			<div class="col-md-4">
				<div class="items">
					<div class="picts"><img class="img-responsive pc-center" src="<?php echo $this->assetBaseurl; ?>exm-testimoni.jpg" alt=""></div>
					<div class="clear height-20"></div>
					<div class="desc">
						<p>Saya menggunakan XADO pada mobil pribadi yaitu Honda CRV tahun 2009. Diperkenalkan dengan XADO oleh salah seorang teman yang memang menggemari Otomotif dan saya pun tertarik untuk mencobanya. Ternyata setelah menggunakan XADO AMC Maximum, tidak hanya mesin lebih tenang plus konsumsi BBM menjadi semakin irit. Sekarang saya juga mencoba produk-produk lain dari XADO.</p>
						<div class="clear height-5"></div>
						<span class="name_human text-center">Morris Rusmanto</span> 
						<div class="clear height-5"></div>
						<span class="status text-center">Pengguna Pribadi</span> 
					</div>
				</div>
			</div>
			<?php } ?>
		</div>
	</div>

	<p>&nbsp;</p>
</div>

backend/protected/views/about/visimisi.php
<section class="outer-inside-middle-content back-white">
  <div class="prelatife container">
    <div class="tops-cont-insidepage"> <div class="clear height-50"></div>
        <div class="height-50"></div>
        <div class="height-50"></div>
        <div class="height-25"></div>
        <div class="tengah insd-container text-center content-up">
          <h1 class="title-pages">ABOUT</h1> <div class="clear height-10"></div>
          <div class="lines-chld-bgrey tengah"></div> <div class="clear height-25"></div>
          <span class="bigs"><?php echo $this->setting['about_header_title'] ?></span> <div class="clear"></div>
          <p><?php echo nl2br($this->setting['about_header_subtitle']) ?></p>
          <div class="clear"></div>
        </div>
    </div>

    <div class="clear"></div>
  </div>

  <div class="back-grey mh500">
    <div class="prelatife container">
        <div class="clear height-50"></div>
        <div class="outers-cont-bottom-abouts">
          <div class="topscont text-center">
            <ul class="list-inline">
              <li><a href="<?php echo CHtml::normalizeUrl(array('/about/index')); ?>">who we are</a></li>
              <li><a href="<?php echo CHtml::normalizeUrl(array('/about/ourteam')); ?>">our team</a></li>
              <li><a href="<?php echo CHtml::normalizeUrl(array('/about/visimisi')); ?>">vision & mission</a></li>
              <li><a href="<?php echo CHtml::normalizeUrl(array('/about/workwithus')); ?>">work with us</a></li>
            </ul>
          </div>
          <div class="clear height-50"></div><div class="height-35"></div>
          <div class="middles">
            
            <div class="mw920 tengah text-center">
                <h2><?php echo $this->setting['about_visimisi_title'] ?></h2> <div class="clear height-30"></div>
                <?php echo $this->setting['about_visimisi_content'] ?>
                <div class="clear height-50"></div>
<?php
$image = AboutImage::model()->findAll();
?>
            <?php foreach ($image as $key => $value): ?>
                <div class="ill-abouts"><img src="<?php echo Yii::app()->baseUrl; ?>/images/about/<?php echo $value->image ?>" alt="" class="img-responsive"></div>
                <div class="clear height-50"></div><div class="height-5"></div>
            <?php endforeach ?>             
                <div class="shares-text">
                  <span class="inline-t">SHARE</span>&nbsp;&nbsp; / &nbsp;&nbsp;<a href="#">FACEBOOK</a>&nbsp;&nbsp; / &nbsp;&nbsp;<a href="#">GOOGLE PLUS</a>&nbsp;&nbsp; / &nbsp;&nbsp;<a href="#">TWITTER</a>
                </div>

                <div class="clear"></div>
            </div>

            <div class="clear"></div>
          </div>

          <div class="clear"></div>
        </div>
      
      <div class="clear"></div> <div class="height-50"></div><div class="height-20"></div>
    </div>
  </div>
</section>

backend/protected/views/about/workwithus.php
<section class="outer-inside-middle-content back-white">
  <div class="prelatife container">
    <div class="tops-cont-insidepage"> <div class="clear height-50"></div>
        <div class="height-50"></div>
        <div class="height-50"></div>
        <div class="height-25"></div>
        <div class="tengah insd-container text-center content-up">
          <h1 class="title-pages">ABOUT</h1> <div class="clear height-10"></div>
          <div class="lines-chld-bgrey tengah"></div> <div class="clear height-25"></div>
          <span class="bigs"><?php echo $this->setting['about_header_title'] ?></span> <div class="clear"></div>
          <p><?php echo nl2br($this->setting['about_header_subtitle']) ?></p>
          <div class="clear"></div>
        </div>
    </div>

    <div class="clear"></div>
  </div>

  <div class="back-grey mh500">
    <div class="prelatife container">
        <div class="clear height-50"></div>
        <div class="outers-cont-bottom-abouts">
          <div class="topscont text-center">
            <ul class="list-inline">
              <li><a href="<?php echo CHtml::normalizeUrl(array('/about/index')); ?>">who we are</a></li>
              <li><a href="<?php echo CHtml::normalizeUrl(array('/about/ourteam')); ?>">our team</a></li>
              <li><a href="<?php echo CHtml::normalizeUrl(array('/about/visimisi')); ?>">vision & mission</a></li>
              <li><a href="<?php echo CHtml::normalizeUrl(array('/about/workwithus')); ?>">work with us</a></li>
            </ul>
          </div>
          <div class="clear height-50"></div><div class="height-35"></div>
          <div class="middles">
            
            <div class="mw920 tengah text-center">
                <h2><?php echo $this->setting['about_workwithus_title'] ?></h2> <div class="clear height-30"></div>
                <?php echo $this->setting['about_workwithus_content'] ?>
                <div class="clear height-50"></div>
<?php
$image = AboutImage::model()->findAll();
?>
            <?php foreach ($image as $key => $value): ?>
                <div class="ill-abouts"><img src="<?php echo Yii::app()->baseUrl; ?>/images/about/<?php echo $value->image ?>" alt="" class="img-responsive"></div>
                <div class="clear height-50"></div><div class="height-5"></div>
            <?php endforeach ?>             
                <div class="shares-text">
                  <span class="inline-t">SHARE</span>&nbsp;&nbsp; / &nbsp;&nbsp;<a href="#">FACEBOOK</a>&nbsp;&nbsp; / &nbsp;&nbsp;<a href="#">GOOGLE PLUS</a>&nbsp;&nbsp; / &nbsp;&nbsp;<a href="#">TWITTER</a>
                </div>

                <div class="clear"></div>
            </div>

            <div class="clear"></div>
          </div>

          <div class="clear"></div>
        </div>
      
      <div class="clear"></div> <div class="height-50"></div><div class="height-20"></div>
    </div>
  </div>
</section>