backend/protected/controllers/HomeController.php
<?php

class HomeController extends Controller
{

	public function actions()
	{
		return array(
			'captcha'=>array(
				'class'=>'CCaptchaAction',
				'backColor'=>0xFFFFFF,
			),
		);
	}

	public function actionCreatecategory()
	{
		for ($i=1; $i < 111; $i++) { 
			$model = new PrdCategoryProduct;
			$model->category_id = 12;
			$model->product_id = $i;
			$model->save(false);
		}
	}

	public function actionInput()
	{
		$data = Table61::model()->findAll();
		foreach ($data as $key => $value) {
			$model = new PrdProduct;
			$model->kode = $value->col_1;
			if ($value->col_7 != '') {
				copy(YiiBase::getPathOfAlias('webroot').'/images/precise/'.$value->col_7.'/COVER.jpg', YiiBase::getPathOfAlias('webroot').'/images/product/'.Slug::create($value->col_1).'-'.Slug::create($value->col_2).'-cover.jpg');
				$model->image = Slug::create($value->col_1).'-'.Slug::create($value->col_2).'-cover.jpg';
			}else{
				$model->image = '';
			}
			$model->harga = $value->col_6;
			$model->harga_coret = 0;
			$model->save(false);
			$dataDesc = new PrdProductDescription;
			$dataDesc->product_id = $model->id;
			$dataDesc->language_id = 2;
			$dataDesc->name = $value->col_2;
			$dataDesc->subtitle = $value->col_3;
			$dataDesc->desc = '<p>'.$value->col_4.'</p>';
			$dataDesc->save(false);
			$dataAttr = explode(',', $value->col_5);
			foreach ($dataAttr as $v) {
				$modelAttr = new PrdProductAttributes;
				$modelAttr->product_id = $model->id;
				$modelAttr->attribute = trim($v);
				$modelAttr->stock = 10;
				$modelAttr->price = $value->col_6;
				$modelAttr->save(false);
				$modelAttr->id_str = $modelAttr->id;
				$modelAttr->save(false);

			}
			if ($value->col_7 != '') {
				for ($i=1; $i < 7; $i++) { 
					$modelImage = new PrdProductImage;
					$modelImage->product_id = $model->id;
					copy(YiiBase::getPathOfAlias('webroot').'/images/precise/'.$value->col_7.'/'.$i.'.jpg', YiiBase::getPathOfAlias('webroot').'/images/product/'.Slug::create($value->col_1).'-'.Slug::create($value->col_2).'-photo'.$i.'.jpg');
					$modelImage->image = Slug::create($value->col_1).'-'.Slug::create($value->col_2).'-photo'.$i.'.jpg';
					$modelImage->save(false);
				}
			}



		}
	}

	public function actionIndex()
	{
		$this->redirect(array('/admin'));
		// $criteria2=new CDbCriteria;
			// $criteria2->with = array('description');
			// $criteria2->order = 'date DESC';
			// $criteria2->addCondition('status = "1"');
			// $criteria2->addCondition('description.language_id = :language_id');
			// $criteria2->params[':language_id'] = $this->languageID;

			// if ($_GET['category']) {
			// 	$criteria = new CDbCriteria;
			// 	$criteria->with = array('description');
			// 	$criteria->addCondition('t.id = :id');
			// 	$criteria->params[':id'] = $_GET['category'];
			// 	$criteria->addCondition('t.type = :type');
			// 	$criteria->params[':type'] = 'category';
			// 	$criteria->order = 'sort ASC';
			// 	$strCategory = PrdCategory::model()->find($criteria);

			// 	// $inArray = PrdProduct::getInArrayCategory($_GET['category']);
			// 	// $criteria2->addInCondition('t.category_id', $inArray);
			// 	$criteria2->addCondition('t.tag LIKE :category');
			// 	$criteria2->params[':category'] = '%category='.$_GET['category'].',%';
			// }else{
			// 	$criteria2->addCondition('t.tag LIKE :category');
			// 	$criteria2->params[':category'] = '%category=35,%';
			// }
			// $pageSize = 8;

			// $product = new CActiveDataProvider('PrdProduct', array(
			// 	'criteria'=>$criteria2,
			//     'pagination'=>array(
			//         'pageSize'=>$pageSize,
			//     ),
			// ));

			// $model = new ContactForm;
			// $model->scenario = 'insert';

		$this->layout='//layouts/column1';
		$this->render('index', array(
			// 'product'=>$product,
			// 'model'=>$model,
		));
	}

	public function actionCategory()
	{
		$this->layout='//layouts/column2';

		$this->render('category', array(
		));
	}

	public function actionProduct()
	{
		$this->layout='//layouts/column2';
		$this->pageTitle = 'Product - '. $this->pageTitle;
		
		$this->render('product', array());
	}

	public function actionProductDetail()
	{
		$this->layout='//layouts/column2';
		$this->pageTitle = 'Product Detail - '. $this->pageTitle;

		$criteria = new CDbCriteria;
        $criteria->with = array('description');
        $criteria->addCondition('t.type = :type');
        $criteria->params[':type'] = 'category';
        $criteria->addCondition('t.id = :id');
		$criteria->params[':id'] = intval($_GET['category']);
        $criteria->order = 't.sort ASC';
        $nCategory = PrdCategory::model()->find($criteria);


		$criteria2=new CDbCriteria;
		$criteria2->with = array('description');
		$criteria2->order = 't.urutan ASC';
		$criteria2->addCondition('t.status = "1"');
		$criteria2->addCondition('description.language_id = :language_id');
		$criteria2->params[':language_id'] = $this->languageID;
		$criteria2->addSearchCondition('t.filter', 'category='. intval($_GET['category']), 'LIKE');

		// ------------------ FILTER --------------------------
		// $get = $_GET;
		// unset($get['category']);
		// $no = 1;
		// foreach ($get as $key => $val) {
		// 	$sql = array();
		// 	if (is_array($get[$key])) {
		// 		foreach ($get[$key] as $value) {
		// 			$sql[] = 't.filter LIKE :filter'.$no;
		// 			$criteria2->params[':filter'.$no] = '%'.$key.'='.$value.'%';
		// 			$no++;
		// 		}
		// 		$criteria2->addCondition(implode(' OR ', $sql));
		// 	}
		// }

		$criteria2->select = "*";
		$criteria2->group = 't.id';

		$product = new CActiveDataProvider('PrdProduct', array(
			'criteria'=>$criteria2,
		    'pagination'=>false,
		));
		
		$this->render('product_detail', array(
			'products' => $product,
			'category'=>$nCategory,
		));
	}
	public function actionSyarat()
	{
		$this->layout='//layouts/column2';

		$this->render('syarat_ketentuan', array(
		));
	}

	public function actionProcess()
	{
		$this->layout='//layouts/column2';
		
		$this->render('process', array(
		));
	}

	public function actionFaq()
	{
		$this->layout='//layouts/column2';

		$criteria=new CDbCriteria;
		$criteria->with = array('description');
		$criteria->order = 't.id ASC';

		$criteria->addCondition('status = "1"');
		$criteria->addCondition('description.language_id = :language_id');
		$criteria->params[':language_id'] = $this->languageID;

		$pageSize = 100000;

		$dataFaq = new CActiveDataProvider('Faq', array(
			'criteria'=>$criteria,
		    'pagination'=>array(
		        'pageSize'=>$pageSize,
		    ),
		));

		$this->render('faq', array(
			'dataFaq'=>$dataFaq,
		));
	}

	public function actionError()
	{
		$this->layout = '//layouts/error';
		if($error=Yii::app()->errorHandler->error)
		{
			if(Yii::app()->request->isAjaxRequest)
				echo $error['message'];
			else{

				$criteria=new CDbCriteria;
				$criteria->with = array('description', 'category', 'categories');
				$criteria->order = 'date DESC';
				$criteria->addCondition('status = "1"');
				$criteria->addCondition('terlaris = "1"');
				$criteria->addCondition('description.language_id = :language_id');
				$criteria->params[':language_id'] = $this->languageID;
				$pageSize = 12;
				$criteria->group = 't.id';
				$product = new CActiveDataProvider('PrdProduct', array(
					'criteria'=>$criteria,
				    'pagination'=>array(
				        'pageSize'=>$pageSize,
				    ),
				));


				$criteria = new CDbCriteria;
				$criteria->with = array('description');
				$criteria->addCondition('t.parent_id = :parent_id');
				$criteria->params[':parent_id'] = 0;
				$criteria->addCondition('t.type = :type');
				$criteria->params[':type'] = 'category';
				$criteria->limit = 3;
				$criteria->order = 'sort ASC';
				$categories = PrdCategory::model()->findAll($criteria);

				$this->layout='//layouts/column2';

				$this->pageTitle = 'Error '.$error['code'].': '. $error['message'] .' - '.$this->pageTitle;
				$this->render('error', array(
					'error'=>$error,
					'product'=>$product,
					'categories'=>$categories,
				));
			}
		}

	}

	public function actionAbout()
	{
		$this->pageTitle = 'About Us - '.$this->pageTitle;
		$this->layout='//layouts/column2';

		$this->render('about', array(	
		));
	}
	
	public function actionQuality()
	{
		$this->pageTitle = 'Quality & Process - '.$this->pageTitle;
		$this->layout='//layouts/column2';

		$this->render('quality', array(	
		));
	}
	
	public function actionProduk()
	{
		$this->pageTitle = 'Produk - '.$this->pageTitle;
		$this->layout='//layouts/column2';

		$this->render('produk', array(	
		));
	}

	public function actionContact()
	{
		$this->pageTitle = 'Contact - '.$this->pageTitle;
		$this->layout='//layouts/column2';
		
		$model = new ContactForm;
		$model->scenario = 'insert';

		if(isset($_POST['ContactForm']))
		{
			if (!isset($_POST['g-recaptcha-response'])) {
				$this->redirect(array('/home/contactus'));
	        }
	        
	        $secret_key = "6LfaqgkUAAAAAEGhdM7GVk6o-jNbidJ9t3xgc0wn";
	        $response=file_get_contents("https://www.google.com/recaptcha/api/siteverify?secret=".$secret_key."&response=".$_POST['g-recaptcha-response']."&remoteip=".$_SERVER['REMOTE_ADDR']);
	        $response = json_decode($response);
	        if($response->success==false)
	        {
	          $model->addError('verifyCode', 'Silahkan verifikasi captcha yang tersedia');
	        }

			$model->attributes=$_POST['ContactForm'];
			if(!$model->hasErrors() AND $model->validate())
			{
				// config email
				$messaged = $this->renderPartial('//mail/contact',array(
					'model'=>$model,
				),TRUE);
				$config = array(
					'to'=>array($model->email, $this->setting['email']),
					'subject'=>'Hi, Contact from '.$model->email,
					'message'=>$messaged,
				);
				if ($this->setting['contact_cc']) {
					$config['cc'] = array($this->setting['contact_cc']);
				}
				if ($this->setting['contact_bcc']) {
					$config['bcc'] = array($this->setting['contact_bcc']);
				}
				// kirim email
				Common::mail($config);

backend/protected/views/home/_form_contact2.php
<!-- start form c -->
<div class="box-form tl-contact-form">
  <div class="mw665">
    <div class="text-left">
    <div class="clear"></div>
  <?php $form=$this->beginWidget('bootstrap.widgets.TbActiveForm',array(
                  'type'=>'',
                  'enableAjaxValidation'=>false,
                  'clientOptions'=>array(
                      'validateOnSubmit'=>false,
                  ),
                  'htmlOptions' => array(
                      'enctype' => 'multipart/form-data',
                  ),
              )); ?>
   <?php echo $form->errorSummary($model, '', '', array('class'=>'alert alert-danger')); ?>
    <?php if(Yii::app()->user->hasFlash('success')): ?>
        <?php $this->widget('bootstrap.widgets.TbAlert', array(
            'alerts'=>array('success'),
        )); ?>
    <?php endif; ?>

    <div class="row default">
      <div class="col-md-6 col-sm-6">
        <div class="form-group">
            <label for="exampleInputName">Name</label>
            <?php echo $form->textField($model, 'name', array('class'=>'form-control')); ?>
        </div>
      </div>
      <div class="col-md-6 col-sm-6">
        
        <div class="form-group">
            <label for="exampleInputEmail">Email</label>
            <?php echo $form->textField($model, 'email', array('class'=>'form-control')); ?>
        </div>
      </div>
    </div>

    <div class="row default">
      <div class="col-md-6 col-sm-6">
        <div class="form-group">
            <label for="exampleInputPhone">Phone</label>
            <?php echo $form->textField($model, 'phone', array('class'=>'form-control')); ?>
        </div>
      </div>
      <div class="col-md-6 col-sm-6">
        <div class="form-group">
            <label for="exampleInputCompany">Company</label>
            <?php echo $form->textField($model, 'company', array('class'=>'form-control')); ?>
        </div>
      </div>
    </div>

    <div class="row default">
      <div class="col-md-12 col-sm-12 col-lg-12">
        <div class="form-group">
            <label for="exampleInputMessage">Message</label> 
            <div class="clear"></div>
            <?php echo $form->textArea($model, 'body', array('class'=>'form-control', 'rows'=>4)); ?>
        </div>
      </div>
      <div class="clear"></div>

      <div class="col-md-12 col-sm-12 col-lg-12">
        <div class="row default">
          <div class="col-md-6 col-sm-6">
            <div class="fright-inpd">
              <div class="form-group mb-0">
                <div class="fleft">
                  <div class="g-recaptcha" data-sitekey="6LewK0EUAAAAABmDgvHxO3OIHJ0dRpyYyu40CvOn"></div>
                </div>
                <div class="clear"></div>
              </div>
            </div>
          </div>
          <div class="col-md-6 col-sm-6">
            <div class="fright">
              <button type="submit" class="btn btn-default btns-submit-bt"></button>
            </div>
          </div>
        </div>

      </div>
    </div>

  <?php $this->endWidget(); ?>
      <div class="clear height-30"></div>
    <div class="clear"></div>
  </div>

  <div class="clear"></div>
</div>

<div class="clear"></div>
</div>
<!-- end form c -->
<script src='https://www.google.com/recaptcha/api.js'></script>

backend/protected/views/home/about.php
<div class="h98"></div>

<section class="inside_cover_pg">
    <div class="pictures prelatife">
        <img src="<?php echo Yii::app()->baseUrl.ImageHelper::thumb(1920,735, '/images/static/'. $this->setting['about_hero_image'] , array('method' => 'adaptiveResize', 'quality' => '90')) ?>" alt="" class="img img-fluid">
    </div>
    <div class="blocks_outer_breadstop">
        <div class="prelatife container">
            <div class="row">
                <div class="col-md-25">
                    <div class="blocks_title prelatife">
                        <div class="inner">
                            <h1><?php echo $this->setting['about_hero_title'] ?></h1>
                        </div>
                    </div>
                </div>
                <div class="col-md-35">
                    <div class="text-right py-2 my-2 right_block">
                        <div class="d-inline-block align-middle">
                            <nav aria-label="breadcrumb">
                              <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="<?php echo CHtml::normalizeUrl(array('/home/index')); ?>">Home</a></li>
                                <li class="breadcrumb-item active" aria-current="page"><?php echo $this->setting['about_hero_title'] ?></li>
                              </ol>
                            </nav>
                        </div>
                        <div class="d-inline-block align-middle px-2">
                        <img src="<?php echo $this->assetBaseurl; ?>vert-liner.jpg" alt="" class="img img-fluid">
                        </div>
                        <div class="d-inline-block align-middle sback">
                            <a onclick="window.history.back();" href="#">back</a>
                            <div class="clearfix"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="home-sec-about-1">
    <div class="py-4"></div>
    <div class="prelative container">
        <div class="row list_data-about-1">
            <div class="col-md-30">
                <div class="pictures">
                    <img class="img img-fluid w-100" src="<?php echo Yii::app()->baseUrl.'/images/static/'. $this->setting['about1_image'] ?>" alt="">
                </div>
            </div>
            <div class="col-md-30">
                <div class="content content-texts pt-5">
                    <?php echo $this->setting['about1_content'] ?>
                </div>
            </div>
        </div>
    </div>
    <div class="prelative container">
        <div class="row list_data-about-2">
            
            <?php for ($i=1; $i < 4; $i++) { ?>
            <div class="col-md-20">
                <div class="pictures">
                    <img class="img img-fluid w-100" src="<?php echo Yii::app()->baseUrl.'/images/static/'. $this->setting['about2_banners_'. $i] ?>" alt="">
                </div>
            </div>
            <?php } ?>

        </div>
    </div>
    <div class="prelative container">
        <div class="row list_data-about-3">
            <div class="col-md-30">
                <div class="content content-texts pt-5">
                    <?php echo $this->setting['about3_content'] ?>
                    <img src="<?php echo $this->assetBaseurl; ?>logo-sap.png" class="img img-fluid" alt="">
                </div>
            </div>
            <div class="col-md-30">
                <div class="pictures">
                    <img class="img img-fluid w-100" src="<?php echo Yii::app()->baseUrl.'/images/static/'. $this->setting['about3_image'] ?>" alt="">
                </div>
            </div>
        </div>
    </div>
</section>
<section class="home-sec-about-2">
    <div class="prelative container">
        <div class="row">
            <div class="col-md-60">
                <div class="outers">
                    <div class="content content-texts">
                        <h4><?php echo $this->setting['about4_title'] ?></h4>
                        <div class="outer row">
                            <div class="col-md-10"></div>
                            <div class="col-md-40 text-center">
                                <?php echo $this->setting['about4_subcontent'] ?>
                            </div>
                            <div class="col-md-10"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="prelative container">
        <div class="row list-data-about">
            <?php for ($i=1; $i < 5; $i++) { ?>
            <div class="col-md-15">
                <div class="outerss">
                    <div class="pictures">
                        <img class="img img-fluid d-block mx-auto" src="<?php echo Yii::app()->baseUrl.'/images/static/'. $this->setting['about4_hl_picture_'. $i] ?>" alt="">
                    </div>
                    <div class="jarak">
                        <div class="content">
                            <h4><?php echo $this->setting['about4_hl_titles_'. $i] ?></h4>
                            <div class="py-1"></div>
                            <p><?php echo $this->setting['about4_hl_desc_'. $i] ?></p>
                        </div>
                    </div>
                </div>
            </div>
            <?php } ?>

        </div>
    </div>
</section>

<section class="home-sec-about-3 outers_back_visionblock py-5">
    <div class="py-4"></div>
    <div class="prelatife container">
        <div class="row">
            <div class="col-md-30">
                <div class="content">
                    <h4>Vision</h4>
                    <?php echo $this->setting['about_visi'] ?>
                </div>
            </div>
            <div class="col-md-30">
                <div class="content">
                    <h4>Mision</h4>
                    <?php echo $this->setting['about_misi'] ?>
                </div>
            </div>
        </div>
        <div class="clearfix clear"></div>
    </div>
</section>

backend/protected/views/home/contact.php
<div class="h98"></div>

<section class="inside_cover_pg">
    <div class="pictures prelatife">
    	<img src="<?php echo Yii::app()->baseUrl.ImageHelper::thumb(1920,735, '/images/static/'. $this->setting['contact_hero_image'] , array('method' => 'adaptiveResize', 'quality' => '90')) ?>" alt="" class="img img-fluid">
    </div>
    <div class="blocks_outer_breadstop">
        <div class="prelatife container">
            <div class="row">
                <div class="col-md-25">
                    <div class="blocks_title prelatife">
                        <div class="inner">
                            <h1><?php echo $this->setting['contact_hero_title'] ?></h1>
                        </div>
                    </div>
                </div>
                <div class="col-md-35">
                    <div class="text-right py-2 my-2 right_block">
                        <div class="d-inline-block align-middle">
                            <nav aria-label="breadcrumb">
                              <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="<?php echo CHtml::normalizeUrl(array('/home/index')); ?>">Home</a></li>
                                <li class="breadcrumb-item active" aria-current="page"><?php echo $this->setting['contact_hero_title'] ?></li>
                              </ol>
                            </nav>
                        </div>
                        <div class="d-inline-block align-middle px-2">
                        <img src="<?php echo $this->assetBaseurl; ?>vert-liner.jpg" alt="" class="img img-fluid">
                        </div>
                        <div class="d-inline-block align-middle sback">
                            <a onclick="window.history.back();" href="#">back</a>
                            <div class="clearfix"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>


<section class="home-sec-contact">
		<div class="prelative container w904">
			<div class="py-4"></div>

			<div class="row">
				<div class="col-md-60">
					<div class="judul">
						<h4>PT. Bumi Menara Internusa</h4>
					</div>
				</div>
			</div>
			
			<div class="row box_info_contacttop">
				<div class="col-md-20">
					<div class="box_item text-center">
						<div class="n_icon text-center"><i class="fa fa-whatsapp"></i></div>
						<div class="texts pt-2">
							<p>Whatsapp<br><a href="https://wa.me/<?php echo str_replace(' ', '', $this->setting['contact_wa']) ?>"><?php echo str_replace('628', '08', $this->setting['contact_wa']) ?> (Click to chat)</a></p>
						</div>
					</div>
				</div>
				<div class="col-md-20">
					<div class="box_item text-center">
						<div class="n_icon text-center"><i class="fa fa-phone"></i></div>
						<div class="texts pt-2">
							<p>Telephone<br><a href="tel:<?php echo str_replace(' ', '', $this->setting['contact_phone']) ?>">+<?php echo $this->setting['contact_phone'] ?></a></p>
						</div>
					</div>
				</div>
				<div class="col-md-20">
					<div class="box_item text-center">
						<div class="n_icon text-center"><i class="fa fa-envelope"></i></div>
						<div class="texts pt-2">
							<p>Email<br> <a href="mailto:<?php echo $this->setting['contact_email'] ?>"><?php echo $this->setting['contact_email'] ?></a></p>
						</div>	
					</div>
				</div>
			</div>
			<div class="py-4"></div>
			<div class="py-2"></div>

		</div>
	</section>

	<section class="home-sec-contact-2">
		<div class="prelative container w904">
			<div class="row">
				<?php for ($i=1; $i < 3; $i++) { ?>
				<div class="col-md-30">
					<div class="box-image">
						<img class="img img-fluid" src="<?php echo Yii::app()->baseUrl.'/images/static/'. $this->setting['contact'.$i.'_pict'] ?>" alt="">
					</div>
					<div class="titles">
						<?php echo $this->setting['contact'.$i.'_desc'] ?>
					</div>
				</div>
				<?php } ?>

				</div>
			</div>
		</div>
	</section>

backend/protected/views/home/index.php
<section class="home-sec-1">
  <div class="py-5"></div>
  <div class="py-4 d-none d-sm-block"></div>
   <div class="prelative container">
    
      <div class="row">
        <div class="col-md-60">
           <div class="judul">
              <h3><?php echo $this->setting['home1_title'] ?></h3>
              <div class="isi">
                 <?php echo $this->setting['home1_subcontent'] ?>
              </div>
           </div>
         </div>
      </div>
       
       <?php 
        $criteria = new CDbCriteria;
        $criteria->with = array('description');
        $criteria->addCondition('t.type = :type');
        $criteria->params[':type'] = 'category';
        // $criteria->limit = 3;
        $criteria->order = 't.sort ASC';
        $nCategory = PrdCategory::model()->findAll($criteria);
       ?>
       <div class="row">
        <?php foreach ($nCategory as $key => $value): ?>
         <div class="col-md-15 col-30">
            <div class="box-content">
               <div class="image">
                <a href="<?php echo CHtml::normalizeUrl(array('/home/productDetail', 'category'=> $value->id)); ?>">
                 <img class="w-100" src="<?php echo Yii::app()->baseUrl.ImageHelper::thumb(298,298, '/images/category/'. $value->image , array('method' => 'adaptiveResize', 'quality' => '90')); ?>" alt="">
                 </a>
             </div>
               <div class="content pt-4">
                  <a href="<?php echo CHtml::normalizeUrl(array('/home/productDetail', 'category'=> $value->id)); ?>"><p><?php echo $value->description->name ?></p></a>
               </div>
            </div>
         </div>
        <?php endforeach ?>
       </div>
   </div>
</section>
<div class="view_buttns_allprod">
   <div class="prelative container">
      <div class="row justify-content-center text-center">
        <div class="col-md-60">
          <a href="<?php echo CHtml::normalizeUrl(array('/home/product')); ?>">View All Product</a>
         </div>
      </div>
   </div>
</div>
<section class="home-sec-2" style="background-image: url('<?php echo $this->assetBaseurl; ?>design2_02.jpg'); padding: 115px;">
   <div class="prelative container">
      <div class="row justify-content-center text-center">
        <div class="col-md-60">
          <img src="<?php echo $this->assetBaseurl; ?>Layer-23-copy-2.png" class="img img-fluid" alt="">
        </div>
      </div>
      <div class="content">
         <h3><?php echo $this->setting['home2_chl_title_top'] ?></h3>
      </div>

      <div class="row">
        <?php for ($i=1; $i < 5; $i++) { ?>
         <div class="col-md-15 col-30">
            <div class="isi">
               <h3><?php echo $this->setting['home2_chl_number_'. $i] ?></h3>
               <p><?php echo $this->setting['home2_chl_txt_'. $i] ?></p>
            </div>
         </div>
        <?php } ?>
      </div>

   </div>
</section>

<?php 
$criteria = new CDbCriteria;
$criteria->with = array('description');
$criteria->addCondition('active = "1"');
$criteria->addCondition('description.language_id = :language_id');
$criteria->params[':language_id'] = $this->languageID;
$criteria->order = 't.date_input DESC';
$criteria->limit = 3;
$data_blog = Blog::model()->findAll($criteria);
?>
<section class="home-sec-3 outers_block_articleshome">
   <div class="prelative container">
      <h4>Latest Blog & Articles</h4>

      <div class="box-image outers_list_news_data">
         <div class="row no-gutters lists_data">
        <?php foreach ($data_blog as $key => $value): ?>
            <div class="col-md-20">
              <div class="items">
                 <div class="pictures">
                    <a href="<?php echo CHtml::normalizeUrl(array('/blog/detail', 'id'=> $value->id)); ?>"><img src="<?php echo Yii::app()->baseUrl.ImageHelper::thumb(432,261, '/images/blog/'. $value->image , array('method' => 'adaptiveResize', 'quality' => '90')); ?>" class="img img-fluid" alt=""></a>
                 </div>
                 <div class="contents">
                    <p><a href="<?php echo CHtml::normalizeUrl(array('/blog/detail', 'id'=> $value->id)); ?>"><?php echo $value->description->title; ?></a></p>
                    <a href="<?php echo CHtml::normalizeUrl(array('/blog/detail', 'id'=> $value->id)); ?>" class="view_art">View Article</a>
                 </div>
               </div>
            </div>
        <?php endforeach ?>          
         </div>
      </div>

   </div>
</section>

<div class="more">
   <div class="prelative container">
      <div class="row justify-content-center text-center">
        <div class="col-md-21"></div>
        <div class="col-md-18">
          <a href="<?php echo CHtml::normalizeUrl(array('/blog/index')); ?>">More Blog & Articles</a>
         </div>
        <div class="col-md-21"></div>
      </div>
   </div>
</div>